//
// Weather Maker for Unity
// (c) 2016 Digital Ruby, LLC
// Source code may be used for personal or commercial projects.
// Source code may NOT be redistributed or sold.
// 
// *** A NOTE ABOUT PIRACY ***
// 
// If you got this asset from a pirate site, please consider buying it from the Unity asset store at https://www.assetstore.unity3d.com/en/#!/content/60955?aid=1011lGnL. This asset is only legally available from the Unity Asset Store.
// 
// I'm a single indie dev supporting my family by spending hundreds and thousands of hours on this and other assets. It's very offensive, rude and just plain evil to steal when I (and many others) put so much hard work into the software.
// 
// Thank you.
//
// *** END NOTE ABOUT PIRACY ***
//

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace DigitalRuby.WeatherMaker
{
    /// <summary>
    /// Makes a directional light a celestial object
    /// </summary>
    [ExecuteInEditMode]
    [RequireComponent(typeof(Light))]
    public class WeatherMakerCelestialObjectScript : MonoBehaviour
    {
        [Tooltip("Whether this is a sun (false if moon)")]
        public bool IsSun;

        [Tooltip("Hint to have the object render in fast mode. Useful for mobile, but not all shaders support it.")]
        public bool RenderHintFast;

        [Range(0.0f, 360.0f)]
        [Tooltip("Rotation about y axis - changes how the celestial body orbits over the scene")]
        public float RotateYDegrees;

        [Tooltip("The orbit type. Only from Earth orbit is currently supported.")]
        public WeatherMakerOrbitType OrbitType = WeatherMakerOrbitType.FromEarth;

        [Range(0.0f, 1.0f)]
        [Tooltip("The scale of the object. For the sun, this is shader specific. For moons, this is a percentage of camera far plane.")]
        public float Scale = 0.02f;

        [Tooltip("Light mode. If set to None, you must set the light intensity yourself.")]
        public WeatherMakerCelestialObjectLightMode LightMode = WeatherMakerCelestialObjectLightMode.Standard;

        [Tooltip("Light color")]
        public Color LightColor = new Color(1.0f / 254.0f, 1.0f / 255.0f, 1.0f / 201.0f, 1.0f);

        [Range(0.0f, 128.0f)]
        [Tooltip("Light power, controls how intense the light lights up the clouds, etc. near the object. Lower values reduce the radius and increase the intensity.")]
        public float LightPower = 8.0f;

        [Tooltip("The intensity of the light of the object at default (full) intensity")]
        [Range(0.0f, 3.0f)]
        public float LightBaseIntensity = 1.0f;

        [Tooltip("The shadow strength of the light of the object at default (full) shadow intensity")]
        [Range(0.0f, 1.0f)]
        public float LightBaseShadowStrength = 0.8f;

        [Range(0.0f, 3.0f)]
        [Tooltip("Light multiplier")]
        public float LightMultiplier = 1.0f;

        [Tooltip("Tint color of the object.")]
        public Color TintColor = Color.white;

        [Range(0.0f, 4.0f)]
        [Tooltip("Tint intensity")]
        public float TintIntensity = 1.0f;

        [Range(0.0f, 100.0f)]
        [Tooltip("Shafts multiplier. Brightens up cloud or fog shafts. Useful for moons.")]
        public float ShaftMultiplier = 1.0f;

        [Tooltip("Horizon multiplier (x = multiplier, y = max intensity, z = power reducer). Increases light intensity in certain effects like clouds as object reaches horizon. Great for brighter sunsets.")]
        public Vector3 HorizonMultiplier;

        /// <summary>
        /// The light for this celestial object
        /// </summary>
        public Light Light { get; private set; }

        /// <summary>
        /// The renderer for this celestial object
        /// </summary>
        public Renderer Renderer { get; private set; }

        /// <summary>
        /// The collider for this celestial object
        /// </summary>
        public Collider Collider { get; private set; }

        /// <summary>
        /// Difference (0-1) of light from last frame. A value of 1 indicates enough difference that shaders should completely re-render.
        /// </summary>
        public float Difference { get; private set; }

        /// <summary>
        /// Whether the orbit type is custom
        /// </summary>
        public bool OrbitTypeIsCustom { get { return OrbitType == WeatherMakerOrbitType.CustomOrthographic || OrbitType == WeatherMakerOrbitType.CustomPerspective; } }

        /// <summary>
        /// Whether the orbit type is perspective (true) or orthographic (false)
        /// </summary>
        public bool OrbitTypeIsPerspective { get { return OrbitType == WeatherMakerOrbitType.FromEarth || OrbitType == WeatherMakerOrbitType.CustomPerspective; } }

        /// <summary>
        /// Whether the object is active
        /// </summary>
        public bool IsActive
        {
            get { return gameObject.activeInHierarchy; }
        }

        /// <summary>
        /// Whether the light for this object is active. A light that is not active is not on.
        /// </summary>
        public bool LightIsActive
        {
            get { return Light.enabled && IsActive; }
        }

        /// <summary>
        /// Whether the light is on. An active light can have a light that is off.
        /// </summary>
        public bool LightIsOn
        {
            get { return LightIsActive && Light.intensity > 0.0f && LightMultiplier > 0.0f && (Light.color.r > 0.0f || Light.color.g > 0.0f || Light.color.b > 0.0f); }
        }

        /// <summary>
        /// Gets the viewport positions of the object.
        /// </summary>
        public Vector3 ViewportPosition
        {
            get; internal set;
        }

        private Vector3 prevHSV;
        private Quaternion prevRotation;

        private void CalculateDifference()
        {
            Vector3 curHSV;
            Color.RGBToHSV(Light.color, out curHSV.x, out curHSV.y, out curHSV.z);
            Quaternion curRot = Light.transform.rotation;
            float diff = Mathf.Abs(prevHSV.x - curHSV.x) + Mathf.Abs(prevHSV.y - curHSV.y) + Mathf.Abs(prevHSV.z - curHSV.z);
            diff += Mathf.Abs(prevRotation.x - curRot.x) + Mathf.Abs(prevRotation.y - curRot.y) + Mathf.Abs(prevRotation.z - curRot.z) + Mathf.Abs(prevRotation.w - curRot.w);
            diff = Mathf.Min(1.0f, diff);
            prevHSV = curHSV;
            prevRotation = curRot;
            Difference = diff * 10.0f;
        }

        private void UpdateInternal()
        {
            if (WeatherMakerLightManagerScript.Instance != null)
            {
                // ensure it is in the list
                if (IsSun)
                {
                    WeatherMakerLightManagerScript.Instance.Moons.Remove(this);
                    if (!WeatherMakerLightManagerScript.Instance.Suns.Contains(this))
                    {
                        WeatherMakerLightManagerScript.Instance.Suns.Add(this);
                    }
                }
                else
                {
                    if (!WeatherMakerLightManagerScript.Instance.Moons.Contains(this))
                    {
                        WeatherMakerLightManagerScript.Instance.Moons.Add(this);
                    }
                    WeatherMakerLightManagerScript.Instance.Suns.Remove(this);
                }
            }
            Light = (Light == null ? GetComponent<Light>() : Light);
            Renderer = (Renderer == null ? GetComponent<Renderer>() : Renderer);
            Collider = (Collider == null ? GetComponent<Collider>() : Collider);

            if (Renderer != null)
            {
                Renderer.enabled = LightIsActive;
                if (RenderHintFast)
                {
                    Renderer.sharedMaterial.EnableKeyword("RENDER_HINT_FAST");
                }
                else
                {
                    Renderer.sharedMaterial.DisableKeyword("RENDER_HINT_FAST");
                }
            }
        }

        private void Awake()
        {
            UpdateInternal();
        }

        private void OnEnable()
        {
            UpdateInternal();
        }

        /// <summary>
        /// Call from the day night cycle manager update
        /// </summary>
        public void UpdateObject()
        {
            UpdateInternal();
            if (Renderer != null && Renderer.sharedMaterial != null)
            {
                Color tintColor = TintColor;
                tintColor.a *= TintIntensity;
                Renderer.sharedMaterial.SetColor(WMS._TintColor, tintColor);
            }
            CalculateDifference();
        }

        /// <summary>
        /// Get a color for a gradient given directional light position
        /// </summary>
        /// <param name="gradient">Gradient</param>
        /// <returns>Color</returns>
        public Color GetGradientColor(Gradient gradient)
        {
            if (gradient == null)
            {
                return WeatherMakerLightManagerScript.EvaluateGradient(gradient, 1.0f);
            }
            float sunGradientLookup = GetGradientLookup();
            return WeatherMakerLightManagerScript.EvaluateGradient(gradient, sunGradientLookup);
        }

        /// <summary>
        /// Get a gradient lookup value given directional light position
        /// </summary>
        /// <returns>Value</returns>
        public float GetGradientLookup()
        {
            if (!LightIsActive)
            {
                return 1.0f;
            }

            float sunGradientLookup;
            CameraMode mode = WeatherMakerScript.ResolveCameraMode();
            if (mode == CameraMode.OrthographicXY && !OrbitTypeIsPerspective)
            {
                sunGradientLookup = transform.forward.z;
            }
            else if (mode == CameraMode.OrthographicXZ && !OrbitTypeIsPerspective)
            {
                sunGradientLookup = transform.forward.x;
            }
            else
            {
                // TODO: Support full spherical world
                sunGradientLookup = -transform.forward.y;
            }
            sunGradientLookup = ((sunGradientLookup + 1.0f) * 0.5f);
            return sunGradientLookup;
        }

        /// <summary>
        /// Get mie dot
        /// </summary>
        /// <returns>Mie dot</returns>
        public float GetSunMieDot()
        {
            return Mathf.Pow(1.0f - Vector3.Dot(Vector3.up, -transform.forward), 5.0f);
        }
    }

    /// <summary>
    /// Celestial object light modes
    /// </summary>
    public enum WeatherMakerCelestialObjectLightMode
    {
        /// <summary>
        /// No lighting, external script must set the light
        /// </summary>
        None = 0,

        /// <summary>
        /// Basic lighting, just set to base light intensity
        /// </summary>
        Basic = 1,

        /// <summary>
        /// Standard lighting, take into account object position, moon phases, etc.
        /// </summary>
        Standard = 2
    }
}
